force-app/main/default/objects/Notice_Rule__c/Notice_Rule__c.object-meta.xml
<CustomObject>
    <label>Notice Rule</label>
    <nameField>
        <label>Notice Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notice Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Change__c.field-meta.xml
<CustomField>
    <fullName>Target_Change__c</fullName>
    <description>The type of change to monitor for in the targeted field.</description>
    <label>Target Change</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any change</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not equal to</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does not contain</fullName>
            </value>
            <value>
                <fullName>Starts with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The field to be monitored on the target records.</description>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Type__c</fullName>
    <description>The type of record (i.e. object) the rule applies to.</description>
    <label>Target Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <description>Value used for comparison to target field value.</description>
    <label>Target Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoticeRuleExtension.cls
public with sharing class NoticeRuleExtension {
    @testVisible ApexPages.StandardController controller; 
    @testVisible private final Notice_Rule__c rule;
    @testVisible private Map<String, List<SelectOption>> mapTargetFieldOptions;
    @testVisible public List<SelectOption> listTargetFieldOptions {get; set;}
    @testVisible public String selectedTargetField {get; set;}
    @testVisible public String selectedTargetChange {get; set;}
    @testVisible public Boolean showTargetValueField {get; set;}
    @testVisible public String titleSectionMain {get; set;}
    
    public NoticeRuleExtension(ApexPages.StandardController stdController) {
        this.controller = stdController;
        this.rule = (Notice_rule__c)controller.getRecord();
        this.mapTargetFieldOptions = new Map<String, List<SelectOption>>();
        this.listTargetFieldOptions = new List<SelectOption>();
        buildPage();
    }

    private void buildPage() {
        buildMapTargetFieldOptions();
        updateTargetFieldOptions();
        updateShowTargetValue();
        updateTitleSectionMain();
    }

    public void buildMapTargetFieldOptions() {
        // Get describe info for target sobject types
        List<Schema.DescribeSObjectResult> dsorList = describeTargetRecordTypes();
        for(Schema.DescribeSObjectResult dsor : dsorList) {
            // Get list of field names for the sobject type
            Map<String, Schema.SObjectField> fieldMap = dsor.fields.getMap();
            List<String> fieldNames = new List<String>(fieldMap.keySet());
            // Build a list of select options using the field names
            List<SelectOption> options = new List<SelectOption>();
            for(String key : fieldNames) {
                // Skip fields that cannot be updated
                if(!fieldMap.get(key).getDescribe().isUpdateable()) { continue; }
                SelectOption o = new SelectOption(key, fieldMap.get(key).getDescribe().getLabel());
                options.add(o);
            }
            options.sort();
            String sObjectName = dsor.getName();
            // Add select options list to map
            mapTargetFieldOptions.put(sObjectName, options);
        }
        // Add blank list of select options to map
        List<SelectOption> blankList = new List<SelectOption>();
        SelectOption blankOption = new SelectOption('', '--None--');
        blankList.add(blankOption);
        mapTargetFieldOptions.put('blank', blankList);
    }

    
    private List<Schema.DescribeSObjectResult> describeTargetRecordTypes() {
        // List picklist values of Target_Record_Type__c
        List<String> objectTypes = new List<String>();
        Schema.DescribeFieldResult descFieldResult = Schema.SObjectType.Notice_Rule__c.fields.Target_Record_Type__c;
        List<Schema.PicklistEntry> pListEntries = descFieldResult.getPicklistValues();
        for(Schema.PicklistEntry entry : pListEntries) {
            objectTypes.add(entry.getValue());
        }
        // Get describe info for all listed sobjecttypes
        List<Schema.DescribeSObjectResult> dsorList = Schema.describeSObjects(objectTypes);
        return dsorList;
    }

    public void updateTargetFieldOptions() {
        String typeSelected = rule.Target_Record_Type__c;
        if (typeSelected == null || typeSelected == '') {
            listTargetFieldOptions = mapTargetFieldOptions.get('blank');
        } else {
            listTargetFieldOptions = mapTargetFieldOptions.get(typeSelected);
        }
    }

    public void updateShowTargetValue() {
        selectedTargetChange = rule.Target_Change__c;
        if (selectedTargetChange == 'Any change') {
            rule.Target_Value__c = '';
            showTargetValueField = false;
        } else {
            showTargetValueField = true;
        }
    }

    public void updateTitleSectionMain() {
        if (rule.Id == null) {
            this.titleSectionMain = 'New';
        } else { 
            this.titleSectionMain = 'Edit'; 
        }
    }

    public PageReference save() {
        rule.Target_Field__c = selectedTargetField;
        return controller.save();
    }

}