force-app/main/default/objects/Notice_Rule__c/Notice_Rule__c.object-meta.xml
<CustomObject>
    <label>Notice Rule</label>
    <nameField>
        <label>Notice Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notice Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Change__c.field-meta.xml
<CustomField>
    <fullName>Target_Change__c</fullName>
    <description>The type of change to monitor for in the targeted field.</description>
    <label>Target Change</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any change</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not equal to</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does not contain</fullName>
            </value>
            <value>
                <fullName>Starts with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The field to be monitored on the target records.</description>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Type__c</fullName>
    <description>The type of record (i.e. object) the rule applies to.</description>
    <label>Target Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <description>Value used for comparison to target field value.</description>
    <label>Target Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notice_Rule_Event__c/Notice_Rule_Event__c.object-meta.xml
<CustomObject>
    <label>Notice Rule Event</label>
    <nameField>
        <label>Notice Rule Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notice Rule Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Notice_Rule_Event__c/fields/Notice_Rule__c.field-meta.xml
<CustomField>
    <fullName>Notice_Rule__c</fullName>
    <label>Notice Rule</label>
    <referenceTo>Notice_Rule__c</referenceTo>
    <relationshipLabel>Notice Rule Events</relationshipLabel>
    <relationshipName>Notice_Rule_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/NoticeRuleChecker.cls
public with sharing class NoticeRuleChecker {
    private List<Notice_Rule_Event__c> events;

    public NoticeRuleChecker() {
        this.events = new List<Notice_Rule_Event__c>();
    }

    public void checkRules(Map<Id,SObject> newRecords, Map<Id,Sobject> oldRecords, List<Notice_Rule__c> rules) {
        for (Notice_Rule__c rule : rules) {
            String recType = rule.Target_Record_Type__c;
            String field = rule.Target_Field__c;
            String change = rule.Target_Change__c;
            String value = rule.Target_Value__c;

            // Check if field is valid for given record type
            if (!isValid(recType, field)) {
                String template = 'ERROR: field "{0}" is invalid for record type "{1}" on notice rule "{2}"';
                List<String> params = new List<String>{field, recType, rule.Id};
                String errorMSG = String.format(template, params);
                System.debug(errorMSG); 
                continue; 
            }

            // Loop records sent by trigger
            for(Id recID : oldRecords.keySet()) {
                SObject newRecord = newRecords.get(recID);
                SObject oldRecord = oldRecords.get(recID);
                
                // If field is not set on either record, continue loop
                List<SObject> recordList = new List<SObject>{newRecord, oldRecord};
                if(!isSetOnOne(recordList, field)) {
                    String template = 'ERROR: field "{0}" is not set on "{1}" record "{2}" sent by trigger';
                    List<String> params = new List<String>{field, recType, oldRecord.Id};
                    String errorMSG = String.format(template, params);
                    System.debug(errorMSG);
                    continue;
                } 

                // Get field values and compare
                String newVal = getValueOrBlank(newRecord, field);
                String oldVal = getValueOrBlank(oldRecord, field);
                switch on change {
                    when 'Any change' {
                        if (newVal != oldVal) {
                            makeRuleEvent(rule.Id);
                        }   
                    }
                    when 'Equals' {
                        if (newVal == value) {
                            makeRuleEvent(rule.Id);
                        }
                    }
                    when 'Not equal to' {
                        if (newVal != value) {
                            makeRuleEvent(rule.Id);
                        }
                    }
                    when 'Contains' {
                        if (newVal.contains(value)) {
                            makeRuleEvent(rule.Id);
                        }
                    }
                    when 'Does not contain' {
                        if (!newVal.contains(value)) {
                            makeRuleEvent(rule.Id);
                        }
                    }
                    when 'Starts with' {
                        if (newVal.startsWith(value)) {
                            makeRuleEvent(rule.Id);
                        }
                    }
                }
            }
        }
        insert events;
    }

    private Boolean isValid(String recType, String field) {
        // Get field map for object type
        List<String> types = new List<String>{recType};
        List<Schema.DescribeSObjectResult> dsorList = Schema.describeSObjects(types);            
        Map<String,Schema.SObjectField> fieldMap = dsorList[0].fields.getMap();
        Boolean result = fieldMap.containsKey(field);
        // If field is invalid for object type
        if (!result) {
            // Log error
            String template = 'ERROR: field "{0}" is invalid for record type "{1}"';
            List<String> params = new List<String>{field, recType};
            String errorMSG = String.format(template, params);
            System.debug(errorMSG);
        }
        return result;
    }

    private Boolean isSetOnOne(List<SObject> records, String field) {
        Boolean result = false;
        for(SObject rec : records) {
            if(rec.isSet(field)) {
                result = true;
                break;
            }
        }
        return result;
    }

    private String getValueOrBlank(SObject record, String field) {
        String result = '';
        if (record.isSet(field)) {
            result = record.get(field).toString();
        }
        return result;
    }

    private void makeRuleEvent(Id ruleId) {
        Notice_Rule_Event__c newEvent = new Notice_Rule_Event__c(Notice_Rule__c = ruleId);
        events.add(newEvent);
    }
    
}