force-app/main/default/objects/Notice_Rule__c/Notice_Rule__c.object-meta.xml
<CustomObject>
    <label>Notice Rule</label>
    <nameField>
        <label>Notice Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notice Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notice_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines whether the notice rule is enforced. Unchecked rules are ignored.</description>
    <inlineHelpText>Unchecked rules are ignored.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Change__c.field-meta.xml
<CustomField>
    <fullName>Target_Change__c</fullName>
    <description>The type of change to monitor for in the targeted field.</description>
    <label>Target Change</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Any change</fullName>
            </value>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>Not equal to</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>Does not contain</fullName>
            </value>
            <value>
                <fullName>Starts with</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Field__c.field-meta.xml
<CustomField>
    <fullName>Target_Field__c</fullName>
    <description>The field to be monitored on the target records.</description>
    <label>Target Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Target_Record_Type__c</fullName>
    <description>The type of record (i.e. object) the rule applies to.</description>
    <label>Target Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Notice_Rule__c/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <description>Value used for comparison to target field value.</description>
    <label>Target Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NoticeRuleGetter.cls
public with sharing class NoticeRuleGetter {  

    public List<Notice_Rule__c> getRules(Schema.SObjectType recType) {
        String recTypeStr = recType.getDescribe().getName();
        List<Notice_Rule__c> rules = [
                SELECT Id,
                    Target_Change__c,
                    Target_Field__c,
                    Target_Record_Type__c,
                    Target_Value__c
                FROM
                    Notice_Rule__c
                WHERE
                    Target_Record_Type__c = :recTypeStr AND
                    Active__c = true
        ];
        return rules;
    }

}